# ╔══════════════════════════════════════════════════════╗
# ║  AKSUMAEL v1.0.0 — Inner Monologue                    ║
# ║  Self-generated thought, persisted as JSON, fed back  ║
# ║  into the vision-LLM prompt as planning context.      ║
# ╚══════════════════════════════════════════════════════╝
#
# Formerly also housed BeliefState, GoalStack, and EpisodicMemory
# "cognitive architecture" stubs. Removed: none of the three were ever
# read back by anything (grep confirmed no caller outside this file and
# test_cognitive.py touched cognitive.belief / cognitive.goals /
# cognitive.episodic) — each was a pure write-to-JSON-every-tick no-op.
# GoalStack's reactive threat/opportunity rules (creeper -> flee,
# diamond_ore -> mine_diamond, ...) duplicated what core/fsm.py already
# does directly and faster from the same YOLO detections, and its own
# EpisodicMemory duplicated (under a confusingly identical name) the
# real, actually-used core/episode_memory.EpisodeMemory. Real goal
# tracking lives in memory/goals.GoalStack; real episode memory lives in
# core/episode_memory.EpisodeMemory. This file now only does the one
# thing that ever fed back into a decision: the inner monologue.

import json
import os
import re
import threading
import time

import config
from core.identity import AKSUMAEL_IDENTITY
from core.llm_router import route_llm_call
from core.capture import push_monologue_line
from core.honcho_context import get_honcho, default_session_id
from core.telegram_channel import get_channel

COGNITIVE_DIR = 'data/cognitive'
MAX_THOUGHTS  = 50

# ── Thought provenance ─────────────────────────────────────────
# Day 3 shipped a confabulation into the Overseer. A training question
# asserted a false premise about the bot's own runtime, the model accepted
# it, core/training_handler.py pushed the answer here through
# push_external(), and recent() handed it back out as a bare sentence in the
# Overseer's "[RECENT THOUGHTS]" block — byte-identical in form to a thought
# generated from live perception. The Overseer had no way to tell the two
# apart and treated the confabulation as an observation.
#
# Day 4's training_handler fix attacks the first half (don't accept the
# premise). This is the second half: an entry now records where it came
# from, and recent(tagged=True) marks anything that is not a self-generated
# thought as an unverified candidate belief, so every consumer downstream of
# this file can scope it. Entries written before this existed carry no
# 'source' key and are read as SOURCE_SELF, which is what they were.
SOURCE_SELF     = 'self'        # generated by update() from live perception
SOURCE_TRAINING = 'training'    # answer to an operator training objective
SOURCE_VOICE    = 'voice'       # answer to a spoken question (axon/hub.py)
SOURCE_EXTERNAL = 'external'    # push_external() with no source given
SOURCE_CODE_CHANGE = 'code_change'  # git post-commit (core/code_awareness.py)

# SOURCE_SELF deliberately has no prefix: the overlay strip, TTS and the
# existing thought log must read exactly as they did before.
#
# SOURCE_CODE_CHANGE is the one non-self source that is *not* marked
# UNVERIFIED: it is read verbatim out of `git log`, not generated by a
# model, so there is no premise for it to have accepted. It still gets a
# prefix, because "my code changed" is a fact about the repository and not
# something the bot saw happen in the world — a consumer that treats it as
# perception would be as wrong as one that treats a Q&A answer that way.
SOURCE_PREFIX = {
    SOURCE_TRAINING: '[training Q&A — UNVERIFIED, not an observation]',
    SOURCE_VOICE:    '[voice Q&A — UNVERIFIED, not an observation]',
    SOURCE_EXTERNAL: '[external — UNVERIFIED, not an observation]',
    SOURCE_CODE_CHANGE: '[code change — from git log, not an observation]',
}

# Substring downstream consumers test for to decide whether a rendered
# monologue block needs the provenance caveat (see memory/context.py).
UNVERIFIED_MARK = 'UNVERIFIED'


def tag_line(entry: dict) -> str:
    """One monologue entry rendered with its provenance prefix."""
    thought = (entry.get('thought') or '').strip()
    prefix  = SOURCE_PREFIX.get(entry.get('source') or SOURCE_SELF)
    return f'{prefix} {thought}' if prefix and thought else thought


# ── Repetition gate ────────────────────────────────────────────
# The monologue prompt is nearly identical tick to tick — same goal, same
# visible labels, same reward — so a local model will happily emit the same
# sentence forever. Observed in the wild as 10+ consecutive ticks of "I need
# to gather wood and food before I can craft the crafting table", which is
# not a thought, it's a stuck loop, and it poisons the planning context that
# reads it back.
#
# After REPEAT_LIMIT identical thoughts in a row, the next prompt carries an
# explicit break instruction. Cheap, local, and it can't wedge: the gate is
# computed fresh from the thought log on every generation, so one different
# sentence clears it.
REPEAT_LIMIT  = 3
REPEAT_NUDGE  = 'Try something different.'


def _thought_key(text: str) -> str:
    """Comparison form of a thought — case, whitespace and trailing
    punctuation folded away.

    Strict equality would miss the actual failure mode: the model re-emits
    the same sentence with a different final period or a stray capital, and
    a byte-comparison would read that as progress.
    """
    return re.sub(r'\s+', ' ', (text or '').strip().lower()).strip('.!? ')


def _load(path, default):
    if os.path.exists(path):
        try:
            with open(path) as f:
                return json.load(f)
        except Exception as e:
            print(f'[COGNITIVE] load error {path}: {e}')
    return default


def _save(path, data):
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as f:
            json.dump(data, f, indent=2)
    except Exception as e:
        print(f'[COGNITIVE] save error {path}: {e}')


class InnerMonologue:
    """One self-generated thought, kicked off every config.MONOLOGUE_EVERY_N_SECONDS
    of wall-clock time (cheap haiku call, ~50 tokens). Gated on wall-clock
    time rather than tick count because tick duration varies from ~0.5s to
    30-40s (LLM-call ticks), so a tick-count gate made the refresh cadence
    wildly unpredictable in practice — sometimes minutes between updates
    (see 2026-07-19, black-strip caption in ui/labeling.py going stale).

    The actual generation call (core.llm_router.route_llm_call, up to
    config.LOCAL_LLM_TIMEOUT=40s) runs in a background daemon thread —
    update() itself only ever kicks the thread off and returns immediately,
    since it's called every tick from the main loop and a 40s local-LLM
    stall there would freeze the display exactly like the KB2040 UART
    write and pre-queue TTS calls did earlier (2026-07-19).

    The most recent real thought is fed back into the next vision-LLM
    planning call as extra context.

    Phase 3 added two side channels, both hanging off this same
    background thread because both are blocking network I/O that must
    never touch the tick loop:

      - **Honcho** (core/honcho_context.py) supplies a cross-session
        self-model, prepended to the prompt as a "Memory:" block and
        refreshed on its own 30s cadence, and receives each generated
        thought so the deriver can build on it.
      - **Telegram** (core/telegram_channel.py) supplies Scott's inbound
        messages, injected as "Scott says:" lines. When Scott has spoken,
        the resulting thought is sent back to him *and* the cadence gate
        is bypassed so he isn't waiting on the next scheduled tick. When
        he hasn't, nothing is sent — the monologue fires every few
        seconds and would otherwise be a firehose."""

    FILE = f'{COGNITIVE_DIR}/inner_monologue.json'

    def __init__(self):
        self.thoughts = _load(self.FILE, [])
        self.claude_call_count = 0      # session total, for health reporting
        self._last_kickoff_ts = 0.0
        self._generating = False
        self._lock = threading.Lock()
        self.session_id = default_session_id()
        self.honcho     = get_honcho()
        self.telegram   = get_channel()
        self._last_honcho_write = 0.0

    def update(self, tick: int, objects: list, action_dict: dict, reward: float,
               goal: str = None, recent_episodes: list = None):
        if self._generating:
            return
        now = time.time()
        # has_pending() is a queue peek, not a drain — a message is never
        # consumed on a tick that then declines to handle it.
        scott_spoke = self.telegram.has_pending()
        if not scott_spoke and now - self._last_kickoff_ts < config.MONOLOGUE_EVERY_N_SECONDS:
            return
        incoming = self.telegram.get_pending_messages() if scott_spoke else []
        self._last_kickoff_ts = now
        self._generating = True
        threading.Thread(
            target=self._generate_and_store,
            args=(tick, objects, action_dict, reward, goal, recent_episodes, incoming),
            daemon=True, name='monologue',
        ).start()

    def _generate_and_store(self, tick, objects, action_dict, reward, goal,
                             recent_episodes, incoming=None):
        incoming = incoming or []
        try:
            # Persist Scott's side first so the thought that answers it is
            # already downstream of it in the session history.
            for m in incoming:
                self.honcho.add_message('scott', m.text, self.session_id)
            memory = self.honcho.get_context(
                self.session_id,
                search_query=incoming[-1].text if incoming else None)
            thought = self._generate_llm(objects, action_dict, reward, goal,
                                          recent_episodes, memory=memory,
                                          incoming=incoming)
            if thought is None:
                thought = self._compose(objects, action_dict, reward)
            with self._lock:
                self.thoughts.append({'tick': tick, 'ts': time.time(),
                                      'thought': thought,
                                      'source': SOURCE_SELF})
                self.thoughts = self.thoughts[-MAX_THOUGHTS:]
                snapshot = list(self.thoughts)
            _save(self.FILE, snapshot)
            push_monologue_line(thought)
            # Reply only when spoken to; the monologue itself is not a
            # notification stream.
            if incoming:
                self.telegram.send_message(thought)
            self._persist_thought(thought, forced=bool(incoming))
        except Exception as e:
            print(f'[COGNITIVE] monologue generation error: {e}')
        finally:
            self._generating = False

    def _persist_thought(self, thought: str, forced: bool = False) -> bool:
        """Write the thought into Honcho, rate-limited. True if it landed.

        The monologue fires every config.MONOLOGUE_EVERY_N_SECONDS (8s).
        Handing Honcho a message that often would keep the deriver
        permanently busy, and each derivation holds mesh-llm — the single
        shared llama.cpp instance — for 2-7s, stalling vision inference
        (docs/HONCHO_SPIKE.md, "The real cost: GPU contention"). So the
        routine path writes at most one thought per
        config.HONCHO_WRITE_EVERY_N_SECONDS. A thought that answers Scott
        is always written: dropping half a conversation from the session
        history is worse than the GPU cost of one derivation."""
        now = time.time()
        every = getattr(config, 'HONCHO_WRITE_EVERY_N_SECONDS', 120)
        if not forced and now - self._last_honcho_write < every:
            return False
        if self.honcho.add_message('assistant', thought, self.session_id):
            self._last_honcho_write = now
            return True
        return False

    def _is_repeating(self) -> bool:
        """True if the last REPEAT_LIMIT thoughts are all the same one."""
        with self._lock:
            recent = [t.get('thought') for t in self.thoughts[-REPEAT_LIMIT:]]
        if len(recent) < REPEAT_LIMIT:
            return False
        keys = [_thought_key(t) for t in recent]
        # An empty key means a blank thought — those are not repetition,
        # and treating them as such would fire the nudge on a fresh log.
        return bool(keys[0]) and len(set(keys)) == 1

    def _compose(self, objects: list, action_dict: dict, reward: float) -> str:
        labels = [o.get('label') for o in objects if o.get('label')]
        seen   = f"I see {', '.join(labels)}." if labels else "I don't see anything notable."
        action = action_dict.get('action', 'wait')
        mood   = 'good' if reward > 0 else 'bad' if reward < 0 else 'neutral'
        return f"{seen} I chose to {action}. That felt {mood} (r={reward:+.2f})."

    def _generate_llm(self, objects: list, action_dict: dict, reward: float,
                       goal: str = None, recent_episodes: list = None,
                       memory: str = None, incoming: list = None) -> str | None:
        if not config.LOCAL_LLM_ENABLED:
            return None
        labels = [o.get('label') for o in objects if o.get('label')]
        fails  = ''
        if recent_episodes:
            bad = [e.get('goal') for e in recent_episodes[-3:] if e.get('outcome') != 'success']
            if bad:
                fails = f' Recent failures: {", ".join(bad)}.'
        # Honcho's cross-session self-model goes in front of the task
        # framing so the model reads it as standing context rather than
        # as part of the current situation.
        mem_block = f'Memory:\n{memory}\n\n' if memory else ''
        if incoming:
            said = '\n'.join(f'Scott says: {m.text}' for m in incoming)
            task = (
                f'{said}\n'
                'You are the inner monologue of a Minecraft AI, and Scott just spoke '
                'to you. In ONE short sentence (max 25 words), answer him directly. '
            )
        else:
            task = (
                'You are the inner monologue of a Minecraft AI. In ONE short sentence '
                '(max 20 words), think out loud about what to do next. '
            )
        # Repetition gate. Placed after the situation and before the output
        # instruction so it reads as the most recent thing said, which is
        # where a small local model actually weights it. Skipped when Scott
        # is being answered — repetition there is his conversation, not a
        # stuck loop, and telling the model to change the subject mid-reply
        # would make it answer a question he did not ask.
        nudge = ''
        if not incoming and self._is_repeating():
            last = ''
            with self._lock:
                if self.thoughts:
                    last = (self.thoughts[-1].get('thought') or '').strip()
            print(f'[COGNITIVE] monologue repeated {REPEAT_LIMIT}x — nudging: {last[:60]!r}')
            nudge = (f'You have now said "{last}" {REPEAT_LIMIT} times in a row. '
                     f'{REPEAT_NUDGE} Do not repeat that sentence or its meaning; '
                     f'name a concrete next action instead. ')
        prompt = (
            f'{AKSUMAEL_IDENTITY}\n'
            f'{mem_block}'
            f'{task}'
            f'Current goal: {goal or "explore"}. Visible: {", ".join(labels) or "nothing"}. '
            f'Last reward: {reward:+.2f}.{fails} '
            f'{nudge}'
            'Respond with only the sentence, no quotes, no preamble.'
        )
        # Generous budget — the model 'thinks' before answering, which can
        # burn several hundred tokens before the actual sentence.
        raw, provider = route_llm_call(prompt, max_tokens=800, timeout=45)
        if provider == 'claude':
            self.claude_call_count += 1
        return raw.strip() if raw else None

    def push_external(self, text: str, source: str = SOURCE_EXTERNAL,
                       persist: bool = False):
        """Append a thought generated outside the normal update() cadence
        (e.g. an Axon voice Q&A answer — see axon/hub.py) directly to disk
        in the same schema update() writes. axon/hub.py runs as its own
        separate process (see its module docstring), so it has no access
        to this live InnerMonologue instance or to core.capture's
        in-process push_monologue_line() queue — writing straight to
        FILE is the only way its answer reaches this process. recent()
        reloads from disk every call (see below), so it shows up in the
        overlay strip on the next tick without any other plumbing.

        `source` is the provenance tag (see SOURCE_* above). Every caller
        here is by definition *not* live perception — it is an answer to
        somebody's question — so the default is already an unverified one.
        Callers that know which kind of Q&A they are should say so.

        `persist=True` also writes the line into Honcho so the deriver
        folds it into episodic memory, on a background thread because
        add_message() is blocking HTTP and most callers here are on the
        tick loop. Off by default: the routine external pushes are Q&A
        answers that the generated thought answering them already covers,
        and every derivation costs 2-7s of exclusive mesh-llm GPU time
        (see _persist_thought). Pass it for the rare event that has no
        other route into the session history — a code change, say."""
        text = (text or '').strip()
        if not text:
            return
        with self._lock:
            self.thoughts = _load(self.FILE, self.thoughts)
            self.thoughts.append({'tick': None, 'ts': time.time(),
                                  'thought': text, 'source': source})
            self.thoughts = self.thoughts[-MAX_THOUGHTS:]
            _save(self.FILE, self.thoughts)
        if persist:
            threading.Thread(target=self._persist_external, args=(text,),
                             daemon=True, name='monologue-persist').start()

    # Waits before each retry of a persisted external push. Sized to clear
    # HonchoContext's own 5s/10s/20s failure backoff, during which
    # add_message() returns False without touching the network — retrying
    # inside that window would just burn the attempts. Observed live on
    # 2026-08-09: a commit made *during* a restart pushed its code-change
    # line while the deriver was still warming, add_messages() timed out at
    # 10s, and the one event this feature exists to remember was dropped.
    PERSIST_RETRY_DELAYS = (15.0, 45.0, 120.0)

    def _persist_external(self, text: str):
        """_persist_thought() off the tick loop, failure-tolerant, retried.

        Honcho being down must never propagate out of a push_external()
        call — the thought is already on disk and in the overlay by then,
        and the memory write is the optional half. But a caller that asked
        for persistence is reporting something that has no other route
        into the session history, so a transient failure is worth a few
        widely-spaced retries rather than a shrug."""
        for i, delay in enumerate((0.0,) + self.PERSIST_RETRY_DELAYS):
            if delay:
                time.sleep(delay)
            try:
                if self._persist_thought(text, forced=True):
                    if i:
                        print(f'[COGNITIVE] external persist landed on retry {i}')
                    return
            except Exception as e:
                print(f'[COGNITIVE] external persist error: {e}')
        print(f'[COGNITIVE] external persist gave up after '
              f'{len(self.PERSIST_RETRY_DELAYS) + 1} tries: {text[:60]!r}')

    def recent(self, n: int = 5, tagged: bool = False) -> str:
        """The last `n` thoughts, newline-joined.

        `tagged=True` prefixes every entry that did not come from live
        perception with its provenance marker. Pass it for anything that
        feeds a decision — the Overseer prompt, the VLM planner history —
        so a Q&A answer cannot be read back as an observation. Leave it
        False for the overlay strip and TTS, which should speak the thought
        and not the bookkeeping.
        """
        with self._lock:
            # Reload from disk rather than trusting self.thoughts alone —
            # push_monologue_line() (below) appends from axon/hub.py's
            # separate process, so a fresh line from there only becomes
            # visible here (and to ui/labeling.py's overlay strip) by
            # re-reading the shared file each call. The file is tiny
            # (MAX_THOUGHTS entries), so this is cheap enough for a
            # once-per-tick read.
            self.thoughts = _load(self.FILE, self.thoughts)
            entries = list(self.thoughts[-n:])
        return '\n'.join(tag_line(t) if tagged else (t.get('thought') or '')
                         for t in entries)


class CognitiveArchitecture:
    """Thin wrapper around InnerMonologue, called once per tick with the
    same signals already flowing through the runtime loop (objects,
    action_dict, reward, goal, recent_episodes)."""

    def __init__(self):
        self.monologue = InnerMonologue()

    def update(self, tick: int, objects: list, action_dict: dict, reward: float,
               goal: str = None, recent_episodes: list = None):
        self.monologue.update(tick, objects, action_dict, reward,
                               goal=goal, recent_episodes=recent_episodes)
